class UserNotFoundException(Exception):
    pass


class DuplicateUserException(Exception):
    pass
